### ISSUE TITLE
The API to Storage doesn't match other providers

### ISSUE THREAD

**Issue by dsboulder** [fog/fog-azure-rm#108]
We're trying to make it possible to use azure storage the same way we use AWS or GCP, which is documented at http://fog.io/storage/.  Unfortunately the methods and objects in the azure storage models don't match the other Fog providers.  Would it be possible to implement the standard `directories` and `files` concept?  A proposed set of API calls would be like so:

```
azure_storage_service = Fog::Storage.new(
  :provider => 'AzureRM',
  :azure_storage_account_name => '<StorageAccountName>'           # Name of an Azure Storage Account
  :azure_storage_access_key => '<StorageAccountKey>'              # Key of an Azure Storage Account
)

azure_storage_service.directories  # should list a bunch of blob "containers"
azure_storage_service.directories.create('newcontainer') # should make a container
azure_storage_service.directories.get('mycontainer').files  # should list blobs
azure_storage_service.directories.get('mycontainer').files.create(
  key: 'some/path/file.txt',
  body: File.open('localfile.txt'),
  public: true|false
)  # should upload a blob
azure_storage_service.directories.get('mycontainer').files.all # returns all blobs
azure_storage_service.directories.get('mycontainer', prefix: 'some/path').files  # returns all blobs under some/path
azure_storage_service.directories.get('mycontainer').files.head('some/path/file.txt') # returns a File object but doesn't download it
azure_storage_service.directories.get('mycontainer').files.get('some/path/file.txt') # returns a File object and downloads its body
azure_storage_service.directories.get('mycontainer').files.head('some/path/file.txt').public_url(Time.now + 3600) # returns a signed URL good for anonymous download for the next hour
azure_storage_service.directories.get('mycontainer').files.get('some/path/file.txt').destroy # delete a blob
```

I know it's a lot of work to change the API, but this would allow you to be used with codebases that are used to using Rackspace, Openstack, GCP, AWS, etc.  What you all think?

**Comment by abbas-sheikh-confiz** [comment]
Hi,

We are evaluating your suggestions, our team is busy for couple of teams. We will respond you soon.

Thanks,

**Comment by dsboulder** [comment]
@abbas-sheikh-confiz I'm going to try to bring this up to @abelhu and Ning and Gil, the people we're working with at Microsoft to support Cloud Foundry.  Maybe they can help get y'all resources, I'm sure you've got a big backlog of work on fog azure.

**Comment by yaxia** [comment]
I will be working on it.

**Comment by shaffan-chaudhry-confiz** [comment]
@dsboulder @yaxia 
Files and Blobs are two different concepts in Azure. So there will be a conflict if we would add Files module in future in fog-azure-rm or end user may get confuse.

**Comment by yaxia** [comment]
Yes, Blobs and Files are different in Azure Storage. However, there is no File service API supported in the azure-storage gem for now. So the best mapping for the directory and file in the Fog is container and blob. We may consider switch to the File APIs when they are ready in the azure-storage gem, otherwise we need call with REST APIs for File directly.

**Comment by AbelHu** [comment]
@yaxia @shaffan-chaudhry-confiz , from my understanding, files in other platforms are same as blobs in Azure storage. We should keep to use files/directories in azure-fog-rm to operate blobs. Azure file service is different and the share folders can be mounted inside VMs directly.

**Comment by yaxia** [comment]
Yes, file service is suitable for sharing data using SMB 3.0 and migrate file share-based applications to the cloud with no code change. However, it doesn't prevent you from calling REST APIs to operate on shares, directories and files directly.

@shaffan-chaudhry-confiz is your concern about the confusing naming or the functionalities that the gem exposes? Is it on your plan that exposes both Blob and File services API via the fog-azure provider?

**Comment by abbas-sheikh-confiz** [comment]
@yaxia, yes we are concerned about confusion in naming for Azure Blob and File service. Naming Azure Blob 'File' would conflict with Azure Storage File service. 
However, currently we do not have plan to add support for Azure File service in Fog Azure RM. In future, we might have to deal with this naming conflict problem once support for File service is required.

**Comment by yaxia** [comment]
@abbas-sheikh-confiz Thanks for clarifying. Understood your concern and I believe the AWS provider has the same issue when they want to support Amazon EFS while they are using bucket and object for now.

The conflicts in PR #95 have been resolved, please take a look. Thanks.

**Comment by AbelHu** [comment]
Thanks @yaxia . @abbas-sheikh-confiz AWS, OpenStack, etc. use directories/files to operate folders and binaries (Just as same as containers/blobs on Azure). If Azure uses different names, current software such as cf-release cannot work on Azure.

**Comment by AbelHu** [comment]
@dsboulder I am working on this to provide the same APIs as AWS, OpenStack, etc.
