### ISSUE TITLE
Different Azure cloud environment support

### ISSUE THREAD

**Issue by AbelHu** [fog/fog-azure-rm#223]
@abbas-sheikh-confiz storage in v0.1.1 only supports `AzureCloud`. Later we will add support for `AzureChinaCloud`, `AzureUSGovernment` and `AzureGermanCloud`. 
To keep consistent with [azure-cli](https://github.com/Azure/azure-xplat-cli/blob/bea341b53149246fb61b95883aa34b72a7e980f2/lib/util/profile/environment.js) and [azure-powershell](https://github.com/Azure/azure-powershell/blob/2eaf6175bc2533b83689120dc7f595ff0bdf8001/src/Common/Commands.Common.Authentication/Models/AzureEnvironment.Methods.cs), I think we should use same names for these environments.
1. By set `environment` in `options` to use different Azure cloud environment
2. The optional values of `environment` should be one of `AzureCloud`, `AzureChinaCloud`, `AzureUSGovernment` or`AzureGermanCloud`.

So below code in this [link](https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm/config.rb#L26-L27) should be updated. How do you think?

```
# Set a CLOUD value from 'Azure', 'AzureChina', 'AzureGermanCloud' and 'AzureUSGovernment'
CLOUD = 'Azure'.freeze
```

**Comment by zeeshan-arshad-confiz** [comment]
@AbelHu it sounds like a good idea. Because it will keep our gem consistent with azure-cli and azure-powershell also we will not be locked to use a single Azure environment for different cloud services at a time.
When are you planning to add support for ```AzureChinaCloud```, ```AzureUSGovernment``` and ```AzureGermanCloud```?

**Comment by AbelHu** [comment]
@zeeshan-arshad-confiz We plan to add support for other environments soon but no ETA for now.

**Comment by AbelHu** [comment]
For names mismatch, I filed an issue [here](https://github.com/Azure/azure-sdk-for-ruby/issues/600)
