### ISSUE TITLE
Move sql module to azure sdk

### ISSUE THREAD

**Issue by samawia-moin-confiz** [fog/fog-azure-rm#229]
As sql server and sql databases are using rest client calls for api calling, and some of the responses have been changed for sql databases, due to which parsing is breaking for sql databses so i suggest we should move sql server and sql databases to azure sdk 0.8.0, as they have added the support of sql in SDK.

**Comment by waqar-haider-confiz** [comment]
Implementation is complete, here is the pull request for the issue.
https://github.com/fog/fog-azure-rm/pull/234
