### ISSUE TITLE
fog-azure gem vs. fog-azure-rm gem vs. azure-sdk-for-ruby gem

### ISSUE THREAD

**Issue by gVien** [fog/fog-azure-rm#233]
I'm trying to determine the right gem to help our team incorporate Azure into our devops app but I see several Azure gems out there and not entirely sure of the right choice. 

After going over several gems, it looks like the [fog-azure gem](https://github.com/fog/fog-azure) is deprecated. Is [Fog-azure-rm gem](https://github.com/fog/fog-azure-rm) the replacement for the fog-azure gem?

Microsoft seems to have their own [Azure sdk gem](https://github.com/Azure/azure-sdk-for-ruby). Issues [229](https://github.com/fog/fog-azure-rm/issues/229) and [232](https://github.com/fog/fog-azure-rm/issues/232) reference the Azure SDK so I'm not sure what the relationship of the Azure SDK and this gem. Is this gem still actively being developed to support Azure?

**Comment by bilal-naeem-confiz** [comment]
Hi @gVien 

`Azure SDK` is being actively developed and it supports all the latest features that are present in Azure. The SDK consists of multiple gems, each focused on providing a single service, such as `azure_mgmt_compute` for compute related services, `azure_mgmt_network` for network related services and so on.

`Fog` on the other hand is a cloud services library. `Fog` provides a simple interface for working with multiple cloud providers. `fog-azure-rm` is being actively developed and supports Azure Resource Manager.

The relationship between `fog-azure-rm` and `Azure SDK` is that `fog-azure-rm` provides an interface to use `Azure SDK`. It makes SDK calls easy by providing the user with a simple interface to work with.

You can choose either `fog-azure-rm` or `Azure SDK` for your use. `fog-azure-rm` will provide you a simple interface to work with the SDK calls. `fog-azure-rm` does not support all the services that are provided by the `Azure SDK`. For those services you can use independent gems provided by the `Azure SDK` to provide support.
