### ISSUE TITLE
Remove unnecessary required attributes from Application Gateway

### ISSUE THREAD

**Issue by zeeshan-arshad-confiz** [fog/fog-azure-rm#236]
Remove unnecessary required attributes from Application Gateway and add some necessary attributes in it.

* Add `subnet_id` attribute in AG `frontend_ip_configuration`
* Add `id` attribute in all objects(listener, ssl_certificate) under application gateway.
* Remove some of unnecessary required statements from `fronend_ip_config` validation in model/application_gateway/gateway.rb file.
* Remove some of unnecessary required statements from `backend_http_settings` validation in model/application_gateway/gateway.rb file.

**Comment by samawia-moin-confiz** [comment]
Removed unnecessary attributes from application gateway and implemented corresponding functionality.
