### ISSUE TITLE
create_or_update_async option for creating VM

### ISSUE THREAD

**Issue by gVien** [fog/fog-azure-rm#255]
I looked over the [source code](https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm/requests/compute/create_virtual_machine.rb) for creating the VM. It looks like the method `create_or_update` was used instead of `create_or_update_async`. I think if this method (`create_virtual_machine`) is used on an application, it would create a delay after hitting the submit button (correct me if I'm wrong) before the web application can be redirected to another page. 

If there is an option to `create_or_update_async`, it would create the VM and then allow us to use the promise feature detailed at [azure computer sdk doc](https://github.com/Azure/azure-sdk-for-ruby/tree/master/management/azure_mgmt_compute) and also allow us to handle any errors. Is there an option to create or update the VM asynchronously (e.g. `create_virtual_machine_async`)? if not, can that feature be added in the next release?

**Comment by samawia-moin-confiz** [comment]
Hi,

Currently, there is no option to create or update the VM asynchronously. We will respond you soon about adding this feature in the gem.

Thank You

**Comment by gVien** [comment]
The Azure Compute SDK doc mentions `create_or_update_async` so can that be used instead of the `create_or_update` method? I haven't fully tested that method so I wouldn't know what behavior it exhibits.

**Comment by gVien** [comment]
@samawia-moin-confiz, I'm curious if there are any updates on this question. I thought you meant Azure SDK doesn't have an option to create or update the VM asynchronously but you meant Fog Azure RM gem. If the feature isn't available, I guess I can use a mixture of Fog (for resource group, storage, etc creation) and Azure SDK (to take advantage of the asynchronous VM methods).

**Comment by abbas-sheikh-confiz** [comment]
@gVien we are evaluating this issue and will respond soon.

**Comment by shaffan-chaudhry-confiz** [comment]
Resolved in this PR: https://github.com/fog/fog-azure-rm/pull/279

**Comment by gVien** [comment]
Thanks for the quick turn around! I'm curious if this will bump up the version to 0.2.8? reinstalling with `gem install fog-azure-rm` doesn't pull the latest changes, so it hasn't been published to rubygem.org?

**Comment by zeeshan-arshad-confiz** [comment]
@gVien we have not published the new gem yet. We will publish the new gem in next couple of days with some more bug fixes. 
Regarding gem version, it will not be 0.2.8 as we have some major changes as well.
We will let you know after publishing the gem. Stay tuned.
