### ISSUE TITLE
Multiple NICs support for service.servers.create

### ISSUE THREAD

**Issue by xsited** [fog/fog-azure-rm#269]
If I did not understand the implementation correctly I apologize in advance. It seems that only one NIC is allowed to be configured when creating a VM.  And a custom one in particular. Perhaps this ticket offers an opportunity further the this great implementation.

**Comment by abbas-sheikh-confiz** [comment]
@xsited 
Yes you are right. Thanks for pointing it out. 
Can you please share more detail about your specific use case, we will address this issue.

Thanks,

**Comment by xsited** [comment]
Thanks.

use case is nat gateway.  if I recall, all the code seems to be there underneath the hood.   it is just that server call does not pass down an array of nics.  here is the similar interface from aws.

```
compute.servers.create ({
                             :name => "instance-#{Time.now.strftime '%Y%m%d-%H%M%S'}",
                             :image_ref => image.id,
                             :flavor_ref => flavor.id,
                             :security_groups => group.id,
                             :user_data => "#!/bin/bash -xe

",
                             :nics => [{ :net_id => net_shared.id }, { :net_id => net_protected.id }],
                             :key_name => options[:key_name]
                             })
```

**Comment by shaffan-chaudhry-confiz** [comment]
Resolved in this PR: https://github.com/fog/fog-azure-rm/pull/280
