### ISSUE TITLE
Managed OS Disk

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [fog/fog-azure-rm#284]
Unless I'm missing something, I don't think it is currently possible to use this library to create a VM with a managed disk for the OS disk, is this a planned feature?

**Comment by 01100010011001010110010101110000** [comment]
Here's some code that creates a managed VM using the Azure Ruby SDK:
```ruby
storage_profile = Azure::ARM::Compute::Models::StorageProfile.new
image_ref = Azure::ARM::Compute::Models::ImageReference.new
image_ref.id = '/subscriptions/f26415d6-0060-42b9-a345-4809b38be41d/resourceGroups/TestRG/providers/Microsoft.Compute/images/managedvm-image-20170308093957'
os_disk = Azure::ARM::Compute::Models::OSDisk.new
os_disk.os_type = 'Linux'
os_disk.name = 'ManagedOSTest-disk0'
os_disk.caching = Azure::ARM::Compute::Models::CachingTypes::ReadWrite
os_disk.create_option = Azure::ARM::Compute::Models::DiskCreateOptionTypes::FromImage
os_disk.disk_size_gb = 128
managed_disk = Azure::ARM::Compute::Models::ManagedDiskParameters.new
managed_disk.storage_account_type = Azure::ARM::Compute::Models::StorageAccountTypes::StandardLRS
os_disk.managed_disk = managed_disk
storage_profile.os_disk = os_disk
storage_profile.image_reference = image_ref
params.storage_profile = storage_profile
```
This requires the use of the image ID instead of the VHD URI, which I know is what you guys currently use for custom images, and in fact I don't think it will work with a custom image created from an unmanaged VM; every time I tried to use such an unmanaged image the call returned `The resource ManagedOSTest cannot be created from Image CentOSTestingImage until Image has been successfully created`

**Comment by abbas-sheikh-confiz** [comment]
Hi,

We are evaluating this and will share update shortly.

Thanks,

**Comment by bilal-naeem-confiz** [comment]
This feature has been added [#290](https://github.com/fog/fog-azure-rm/pull/290)
