### ISSUE TITLE
fog-core dependency

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [fog/fog-azure-rm#285]
I am using this library in [Foreman Azure RM](https://github.com/01100010011001010110010101110000/foreman_azure_rm)
to add ARM as a compute resource for [The Foreman](https://github.com/theforeman/foreman). Foreman's current fog-core version is pegged at 1.42.0, and this library's fog-core version is pegged to ~> 1.43.0, which is somewhat problematic for development. 
The changelog for fog-core to 1.43 does not seem to mention anything which would affect this library, and I would like to know if you would consider downgrading your fog-core dependency to ~> 1.42.0 or something similar to allow for compatibility with The Foreman

**Comment by bilal-naeem-confiz** [comment]
Hi @01100010011001010110010101110000 

I have looked into your request about downgrading the fog-core version to 1.43.0. As it stands right now, we are not going to do that. What you can do however, is clone this repo, change the version of fog-core in the gemspec to 1.42.0, build and install the gem.
If I may ask about your development environment, if you are using fog-core 1.42.0, it should be easy for you to upgrade it to 1.43.0 as it does not include any breaking changes.
If you have any queries, please let me know and I will get back to you soon.

Thanks

**Comment by 01100010011001010110010101110000** [comment]
For the purposes of development, I just bumped the version of fog-core in my development install of Foreman to 1.43. Unfortunately, doing that in our production install of Foreman is not acceptable from a best practices standpoint, and so I will probably just build a version of your gem with the dependency downgraded to 1.42 while I wait for the guys at The Foreman to bump their fog-core version. Thanks for your time
