### ISSUE TITLE
Make all other Azure methods (deallocate, stop, delete, etc.) asyncronous

### ISSUE THREAD

**Issue by gVien** [fog/fog-azure-rm#288]
A while back I requested to allow [creating a VM asynchronously](https://github.com/fog/fog-azure-rm/issues/255). Can we add the sync feature to all the other methods such as deallocate, stop, delete, etc. as shown here https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm/models/compute/server.rb? It seems to me that the async methods are available on the [Azure SDK](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/virtual_machines.rb).

**Comment by bilal-naeem-confiz** [comment]
Hi @gVien 
After going through the Azure SDK, the async methods are indeed available. The process of adding async requests for all the other methods will be quite similar to what we did for `create_or_update`. I will discuss this with the team and get back to you shortly.
Thanks

**Comment by gVien** [comment]
I'm curious if there are any updates on this issue?

**Comment by bilal-naeem-confiz** [comment]
Hi @gVien 

Yes we have made progress on this issue. It will be released in the next version of the gem.

**Comment by bilal-naeem-confiz** [comment]
Hi @gVien 

The compute methods for server have been made asynchronous. You can see the changes in the PR[#294](https://github.com/fog/fog-azure-rm/pull/294)
