### ISSUE TITLE
Add Support to Attach Managed Data Disk to VM

### ISSUE THREAD

**Issue by abbas-sheikh-confiz** [fog/fog-azure-rm#298]
Presently, Fog ARM does not allow to attach managed data disk to a VM.
Add support to attach managed DD to VM.

**Comment by phanindrakalva** [comment]
is this fixed? is there a another way to attach the managed disks to vm in ruby?

**Comment by bilal-naeem-confiz** [comment]
@phanindrakalva we are currently working on this issue. We will generate a PR for this issue as soon as it is done.

**Comment by bilal-naeem-confiz** [comment]
This has been added. PR #326
