### ISSUE TITLE
Add New Repo Members

### ISSUE THREAD

**Issue by abbas-sheikh-confiz** [fog/fog-azure-rm#299]
Hi @geemus,

I hope you are doing great, please add following github users as repo members.
dandagopi, rameshjanjyam, sleepyorion, azeem-sajid-confiz, muhammad-asad-confiz, maham-nazir-confiz

Thanks,

**Comment by geemus** [comment]
I hope you are doing great also. I've sent invites for all of those users, just let me know if you need anything else.
Thanks!
wes
