### ISSUE TITLE
Add Support for Managed Availability Set

### ISSUE THREAD

**Issue by abbas-sheikh-confiz** [fog/fog-azure-rm#302]
In Fog ARM, while creating availability set we are ONLY creating un-managed availability set(default). When we add a managed OS disk VM to this availability set, we are getting following error

> Addition of a VM with managed disks to non-managed Availability Set or addition of a VM with blob based disks to managed Availability Set is not supported. Please create an Availability Set with 'Aligned' SKU in order to add a VM with managed disks to it. Type: MsRestAzure::AzureOperationError 

Add option to create managed availability set as well so that managed OS disk VMs can be added to it. Here is the relevant [API link](https://docs.microsoft.com/en-us/rest/api/compute/availabilitysets/availabilitysets-create)

**Comment by bilal-naeem-confiz** [comment]
This issue has been resolved in [PR#308](https://github.com/fog/fog-azure-rm/pull/308)
