### ISSUE TITLE
How to increase os_disk size

### ISSUE THREAD

**Issue by phanindrakalva** [fog/fog-azure-rm#317]
is there a way to increase os disk size while creating a vm?

**Comment by bilal-naeem-confiz** [comment]
Hi @phanindrakalva 
Currently fog-azure-rm does not have support to set the size of the os disk when creating a VM. This support will be added in the future.
I will keep this issue open for reference purposes.

**Comment by bilal-naeem-confiz** [comment]
Hi @phanindrakalva 
This issue is being catered in #321

**Comment by phanindrakalva** [comment]
Thank you @bilal-naeem-confiz

**Comment by phanindrakalva** [comment]
@bilal-naeem-confiz the os_disk_size is only for managed disks or it can be used for blob's as well?

**Comment by bilal-naeem-confiz** [comment]
@phanindrakalva it can be used for both managed disks and blob's
