### ISSUE TITLE
Bundler could not find compatible versions for gem "mime-types"

### ISSUE THREAD

**Issue by bingosummer** [fog/fog-azure-rm#359]
I'm trying to use the version `0.3.9` of fog-azure-rm in another project [cloud_controller_ng](https://github.com/cloudfoundry/cloud_controller_ng).
In https://github.com/cloudfoundry/cloud_controller_ng/blob/master/Gemfile#L19, `'mime-types', '~> 2.6.2'` is needed, which causes the following error.

My question is that can fog-azure-rm use a newer version of mime-types?
If so, I think, the issue is resolved.
If not, do you have any suggestions to resolve the issue?
Thanks.

```
Bundler could not find compatible versions for gem "mime-types":
  In snapshot (Gemfile.lock):
    mime-types (= 2.6.2)

  In Gemfile:
    mime-types (~> 2.6.2)

    mime-types (~> 2.6.2) x86_64-darwin-14

    mime-types (~> 2.6.2) x86_64-darwin-16

    mime-types (~> 2.6.2) x86_64-linux

    fog-azure-rm (= 0.3.9) was resolved to 0.3.9, which depends on
      mime-types (= 1.25)

    fog-azure-rm (= 0.3.9) was resolved to 0.3.9, which depends on
      mime-types (= 1.25) x86_64-darwin-14

    fog-azure-rm (= 0.3.9) was resolved to 0.3.9, which depends on
      mime-types (= 1.25) x86_64-darwin-16

    fog-azure-rm (= 0.3.9) was resolved to 0.3.9, which depends on
      mime-types (= 1.25) x86_64-linux

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by abbas-sheikh-confiz** [comment]
Hey @bingosummer 
We are working on altogether removing dependency on mime-types. Please stay tuned.

**Comment by bilal-naeem-confiz** [comment]
Hi @bingosummer 
The latest version of fog-core has been released (2.0.0). We are testing our fog-azure-rm gem using that. If everything works out smoothly, then we will remove the dependency that we have on mime-types and that will resolve the issue that you are currently facing.
Thanks

**Comment by bingosummer** [comment]
@bilal-naeem-confiz How is the test going?

**Comment by tcdowney** [comment]
@bilal-naeem-confiz just wondering if you have any updates for this. Thanks!

**Comment by yelvert** [comment]
2.5 years now, where is this?

**Comment by sethboyles** [comment]
@geemus I think this can be closed

**Comment by geemus** [comment]
Thanks!
