### ISSUE TITLE
lib/fog/azurerm/models/compute/server.rb cannot list windows machines

### ISSUE THREAD

**Issue by mattohope** [fog/fog-azure-rm#36]
line 41 of lib/fog/azurerm/models/compute/server.rb assumes that the machine is a linux box and breaks if retrieving details of a windows host.

Current code:
hash['disable_password_authentication'] = vm['properties']['osProfile']['linuxConfiguration']['disablePasswordAuthentication']

Proposed "Quick Fix"
if vm['properties']['osProfile']['linuxConfiguration']
                hash['disable_password_authentication'] = vm['properties']['osProfile']['linuxConfiguration']['disablePasswordAuthentication']
else
                hash['disable_password_authentication'] = false
end

**Comment by abbas-sheikh-confiz** [comment]
Hi matthope, 

We are looking into this and will resolve it soon. 

thanks for pointing out.

**Comment by shaffan-chaudhry-confiz** [comment]
Hi @mattohope,

We have resolved this issue in this Pull Request: https://github.com/fog/fog-azure-rm/pull/54

**Comment by mattohope** [comment]
sorry i realized that i never came back to you about this, i have tested and this is no longer an issue
