### ISSUE TITLE
Fog ARM Access

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [fog/fog-azure-rm#365]
Hi @geemus,

Please give contributor access to the following users
- maham-nazir-confiz (maham.nazir@confiz.com)
- muhammad-asad-confiz (muhammad.asad@confiz.com)

Thanks

**Comment by geemus** [comment]
@bilal-naeem-confiz I sent an invite to maham-nazir-confiz, the interface says there is already an invite pending to muhammad-asad-confiz. Just let me know if you need anything else, thanks!

**Comment by bilal-naeem-confiz** [comment]
Thanks @geemus
