### ISSUE TITLE
public ip is not assigned to nic

### ISSUE THREAD

**Issue by mattohope** [fog/fog-azure-rm#37]
following this example to create a network interface with a public ip:

    nic = azure_network_service.network_interfaces.create(
        name: '<Network Interface name>',
        resource_group: '<Resource Group name>',
        location: 'eastus',
        subnet_id: '/subscriptions/<Subscriptionid>/resourceGroups/<Resource Group name>/providers/Microsoft.Network/virtualNetworks/<Virtual Network name>/subnets/<Subnet name>',
        ip_configuration_name: '<Ip Configuration Name>',
        private_ip_allocation_method: 'Dynamic'
 )

Even though we are passing in a per-configured "ip_configuration_name" the Network Interface in the Azure console shows that Public IP addresses are disabled, we have to manually enable and assign the Public IP resource.

**Comment by abbas-sheikh-confiz** [comment]
Hi @mattohope, yes this is an issue. We will resolve it soon.

Thanks for pointing out.

**Comment by adnan-khalil-confiz** [comment]
Hi @mattohope, This issue is fixed here. https://github.com/fog/fog-azure-rm/pull/60
You can verify it by pulling latest code from here and building it yourself. Will add it in the next release.

**Comment by adnan-khalil-confiz** [comment]
Will close it once verified.

**Comment by mattohope** [comment]
We have checked out the latest code and tested it, we now have an assigned public IP address :)

**Comment by adnan-khalil-confiz** [comment]
Great. Closing the issue now.
