### ISSUE TITLE
Check the virtual machine status

### ISSUE THREAD

**Issue by mbrehovsky** [fog/fog-azure-rm#38]
Hello,
is it possible to check the status of virtual machine and determine if it is Powered on or Powered off using this gem?

**Comment by abbas-sheikh-confiz** [comment]
Hi @mbrehovsky we are looking into this and will implement this feature soon.

Thanks,

**Comment by haider-ali-confiz** [comment]
Hi  @mbrehovsky,

We have resolved this issue in this Pull Request: #59 . 
The gem is not updated on rubygems.org. You can install gem using GitHub.
Please verify.
