### ISSUE TITLE
VHDs management in storage account

### ISSUE THREAD

**Issue by mbrehovsky** [fog/fog-azure-rm#39]
Are you planning to add support for VHDs management. Would be very handy to be able to list, delete vhds.

**Comment by zeeshan-arshad-confiz** [comment]
Hi @mbrehovsky 

VHDs are also blobs. We have list and delete blob functionality in fog-azure-rm. We can use blobs to manage VHDs. There is no separate API/SDK calls for VHD management in Azure Resource Manager.

Thanks
