### ISSUE TITLE
Still mime-types conflict

### ISSUE THREAD

**Issue by WalterS** [fog/fog-azure-rm#390]
When loading fog/azurerm and fog/google, the following error pops up:
```
Gem::ConflictError: Unable to activate fog-azure-rm-0.4.8, because mime-types-3.1 conflicts with mime-types (~> 1.25)
```

**Comment by WalterS** [comment]
When I set the mime-types dependency to `'~> 3', '>= 3.0'`, I get ```Gem::ConflictError: Unable to activate fog-azure-rm-0.4.9, because fog-json-1.2.0 conflicts with fog-json (~> 1.0.2)```.
When I set the fog-json dependency to `'~> 1', '>= 1.0'`, I get ```Gem::ConflictError: Unable to activate azure-storage-0.11.5.preview, because nokogiri-1.8.4 conflicts with nokogiri (~> 1.6.0)```.
Only if I remove this depende3ny completely, I get a more or less clean built. with the following complaints: 
```WARNING:  no email specified
WARNING:  pessimistic dependency on minitest (~> 5.8.4, development) may be overly strict
  if minitest is semantically versioned, use:
    add_development_dependency 'minitest', '~> 5.8', '>= 5.8.4'
WARNING:  open-ended dependency on simplecov (>= 0, development) is not recommended
  if simplecov is semantically versioned, use:
    add_development_dependency 'simplecov', '~> 0'
WARNING:  pessimistic dependency on codeclimate-test-reporter (~> 1.0.0, development) may be overly strict
  if codeclimate-test-reporter is semantically versioned, use:
    add_development_dependency 'codeclimate-test-reporter', '~> 1.0', '>= 1.0.0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
```

**Comment by geemus** [comment]
@WalterS Did the dependency bump you submitted resolve this? Thanks!

**Comment by dmitryshagin** [comment]
Still in conflict. Why do we need the unsupported 1.x version of MIME-types? Need to switch to a newer one, or even drop explicit version, or change it from `~>` to `>=`.

**Comment by sethboyles** [comment]
@geemus I think this can be closed

**Comment by geemus** [comment]
Thanks!
