### ISSUE TITLE
Public IP is mandatory

### ISSUE THREAD

**Issue by mattohope** [fog/fog-azure-rm#65]
The Server creation requires a public IP configuration, there are a number of use cases where VM's should not have a public IP address.

Can this be made optional

**Comment by adnan-khalil-confiz** [comment]
Hi @mattohope, This issue is fixed here. https://github.com/fog/fog-azure-rm/pull/68
The gem is not updated on rubygems.org. Will update it in a day or two. You can install gem using GitHub.
Plz verify.

**Comment by mattohope** [comment]
Thanks you very much for your speedy implementation, I'll test this and report back.

Thanks again

**Comment by mattohope** [comment]
sorry i realized that i never came back to you about this, public IP is not longer mandatory, i'll close this issue
