### ISSUE TITLE
Enabling blob features of Azure storage

### ISSUE THREAD

**Issue by yaxia** [fog/fog-azure-rm#79]
Hey, since there is support for managing storage accounts, I am going to add support for the Azure storage blob features in this gem. 

The storage client will be created by:
```ruby
azure_storage_client = Fog::Storage.new({
  :provider => 'AzureRM',
  :azure_storage_account_name => YOUR_AZURE_STORAGE_ACCOUNT_NAME,
  :azure_storage_access_key => YOUR_AZURE_STORAGE_ACCESS_KEY
})
```
The APIs I am going to work on are:
```ruby
azure_storage_client.create_container
azure_storage_client.delete_container
azure_storage_client.get_container_properties
azure_storage_client.create_block_blob
azure_storage_client.get_blob
azure_storage_client.delete_blob
azure_storage_client.get_blob_properties
```

If you don't have concern, I will start coding and submit PR later. Thanks.

+@devigned for awareness

**Comment by shaffan-chaudhry-confiz** [comment]
Hello Yang,

You can add these features in the gem. You are also supposed to add unit tests of your code as mentioned in our CONTRIBUTING.md:
[](https://github.com/fog/fog-azure-rm/blob/master/CONTRIBUTING.md)

Feel free to ask questions. Thanks.

**Comment by yaxia** [comment]
Thanks for reviewing and merging the code for storage containers.
