### ISSUE TITLE
Add support for getting/setting blob properties

### ISSUE THREAD

**Issue by yaxia** [fog/fog-azure-rm#91]
I saw you added the support for getting/setting blob metadata. I am going to work on the functions of getting/setting blob properties. Does it conflicts with the plan in your team?

**Comment by samawia-moin-confiz** [comment]
Hi Yang,

You can add support for getting/setting blob properties. There will no conflict with our plan. Before starting work on the features, please create an issue with all the features you are planning to work on.

**Comment by AbelHu** [comment]
@yaxia I think this can be closed now.
